WITH TEMP AS (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
                   FROM REST_INFO
                   GROUP BY FOOD_TYPE)

SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM REST_INFO AS I
    JOIN TEMP AS T
WHERE I.FOOD_TYPE = T.FOOD_TYPE AND I.FAVORITES = T.FAVORITES
ORDER BY FOOD_TYPE DESC