WITH TEMP AS (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
             FROM FOOD_ORDER 
             WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
             GROUP BY PRODUCT_ID
             )

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * T.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
    JOIN TEMP AS T
WHERE P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID

