-- 코드를 입력하세요

WITH TEMP AS (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
          FROM USED_GOODS_BOARD 
            WHERE STATUS = 'DONE'
          GROUP BY WRITER_ID
            HAVING TOTAL_SALES>=700000)

SELECT U.USER_ID, U.NICKNAME, T.TOTAL_SALES
FROM USED_GOODS_USER AS U
    JOIN TEMP AS T
WHERE U.USER_ID = T.WRITER_ID
ORDER BY T.TOTAL_SALES


    