-- 코드를 입력하세요

WITH MAXPRICE AS (SELECT CATEGORY, MAX(PRICE) AS PRICE
              FROM FOOD_PRODUCT
              GROUP BY CATEGORY
                  HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
 )

SELECT P.CATEGORY, P.PRICE AS MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT AS P
    JOIN MAXPRICE AS M
WHERE P.PRICE = M.PRICE AND P.CATEGORY = M.CATEGORY
ORDER BY MAX_PRICE DESC;